name: Family Budget App Staging [Bundling] Pipeline

on:
  pull_request:
    types:
      - closed

jobs:

  #### Intention is to check what alias has been added to the commit message ####
  check-commit-message:
    name: Check Commit Message
    runs-on: ubuntu-latest
    outputs:
      get-commit-message: ${{ steps.get-commit-message.outputs.headCommitMsg }}
      check-bundle-alias: ${{ steps.check-bundle-alias.outputs.bundle_present }}

    steps:
      - name: Check Commit Message
        id: check-commit-message
        uses: actions/checkout@v2

      - name: Get Commit Message
        id: get-commit-message
        run: echo "::set-output name=headCommitMsg::$(git show -s --format=%s)"

      - name: Check for "bundle" alias
        id: check-bundle-alias
        run: |
          if [[ "${{ steps.get-commit-message.outputs.headCommitMsg, '[BUNDLE]' }} ]]; then
            echo "Commit message contains 'BUNDLE'"
            echo "::set-output name=bundle_present::true"
          else
            echo "Commit message does not contain 'BUNDLE'"
            echo "::set-output name=bundle_present::false"
          fi

  #### Run the android bundle capgo command
  bundle-android:
    name: Bundle Android
    needs: check-commit-message
    runs-on: ubuntu-latest
    if: ${{ needs.check-commit-message.outputs.check-bundle-alias == 'true' }}

    steps:
      - name: Checkout source
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16.x

      - name: Install Ionic
        run: npm install -g @ionic/cli

      - name: Install Ionic
        run: npm install -g @capgo/cli@latest

      - name: Install app dependencies
        run: npm install --force

      - name: Sync Android
        run: ionic cap sync android -c=development

      - name: Create Release
        id: create_release
        run: npx @capgo/cli@latest bundle upload -a ${{ secrets.CAPGO_TOKEN }} -c production